name: mecago
description: "Application premium d'entretien et diagnostic automobile assisté par IA."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation & Shell Routing
  go_router: ^13.2.0

  # Base de données locale & Persistance des voitures
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.0

  # Services Cloud Firebase Core & Authentication
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0

  # Notifications push locales
  flutter_local_notifications: ^16.3.2

  # Export PDF premium
  pdf: ^3.10.7
  printing: ^5.12.0

  # Affiliation & liens externes
  url_launcher: ^6.2.4

  # Détection réseau
  connectivity_plus: ^5.0.2

  # Utilitaires
  intl: ^0.18.1
  uuid: ^4.3.3

  # Icônes premiums standardisées
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Déclaration de la police d'écriture d'excellence Apple Style
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700
