// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_NE-V2hUeUojwmEXgyONcc024yuPT5XQ',
    appId: '1:622529761930:web:64e8e4e6023e04448a1373',
    messagingSenderId: '622529761930',
    projectId: 'mecago-ai',
    authDomain: 'mecago-ai.firebaseapp.com',
    storageBucket: 'mecago-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6OgFBEr4q9Eo31keEHgq1YL-gXYSwgxk',
    appId: '1:622529761930:android:7febff91865a31908a1373',
    messagingSenderId: '622529761930',
    projectId: 'mecago-ai',
    storageBucket: 'mecago-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtUUKcIknfK-sH_G4imrjVbgX3sfSw8wo',
    appId: '1:622529761930:ios:1b0838a7bba3c1378a1373',
    messagingSenderId: '622529761930',
    projectId: 'mecago-ai',
    storageBucket: 'mecago-ai.firebasestorage.app',
    iosBundleId: 'com.example.mecago',
  );
}
